from talon import Context, Module, actions
import re

mod = Module()


def escape():
    actions.key("escape")

def enter():
    actions.key("enter")

symbols = {
    # TODO: I'm not sure why we need these, I think it has something to do with
    # Dragon. Possibly it has been fixed by later improvements to talon? -rntz
    "`": "`",
    ",": ",",  # <== these things
    "back tick": "`",
    "comma": ",",
    # Workaround for issue with conformer b-series; see #946
    "coma": ",",
    "full stop": ".",
    "semicolon": ";",
    "colon": ":",
    "forward slash": "/",
    "question mark": "?",
    "exclamation mark": "!",
    "exclamation point": "!",
    "asterisk": "*",
    "hash sign": "#",
    "number sign": "#",
    "percent sign": "%",
    "at sign": "@",
    "and sign": "&",
    "ampersand": "&",
    # Currencies
    "dollar sign": "$",
    "pound sign": "£",
    "hyphen": "-",
    "L paren": "(",
    "left paren": "(",
    "R paren": ")",
    "point": ".",
    "sing quote": "'",
    "single quote": "'",
    "apostrophe": "'",
    "L square": "[",
    "left square": "[",
    "brack": "[",
    "bracket": "[",
    "left bracket": "[",
    "right square": "]",
    "r brack": "]",
    "r bracket": "]",
    "right bracket": "]",
    "minus": "-",
    "dash": "-",
    "equals": "=",
    "plus": "+",
    "grave": "`",
    "tilde": "~",
    "r brace": "}",
    "angle": "<",
    "langle": "<",
    "less than": "<",
    "dangle": ">",
    "R angle": ">",
    "right angle": ">",
    "greater than": ">",
    "star": "*",
    "hash": "#",
    "percent": "%",
    "math hat": "^",
    "amper": "&",
    "pipe": "|",
    "dub quote": '"',
    "quote": '"',
    "quad": '"',
    "twin": "'",
    "double quote": '"',
    # Currencies
    "dollar": "$",
    "pound": "£",
    # Brendan
    "item": ", ",
    "semco": ";",
    "question": "?",
    "slash": "/",
    "backslash": "\\",
    "bang": "!",
    "down score": "_",
    "underscore": "_",
    "under": "_",
    "you score": "_",
    "paren": "(",
    "darren": ")",
    "invoke": "(",
    "round": "(",
    "sound": ")",
    "hound": ")",
    "squirrel": "{",
    "squirrely": "{",
    "girl": "}",
    "girly": "}",
    "slice": "[",
    "dice": "]",
    "rice": "]",
    "scope": "::",
    "period": ".",
    "dot": ".",
    "prick": ".",
    "punk": ".",
    "equality": "==",
    "less": "<",
    "lesseek": "<=",
    "greater": ">",
    "greatereek": ">=",
    "slash": "/",
    # Brendan Spaced
    "space": " ",
    "leader": " ",
    "is type": ": ",
    "item": ", ",
    "semco": ";",
    "question": "?",
    "backslash": "\\",
    "bang": "!",
    "tilde": "~",
    "down score": "_",
    "underscore": "_",
    "under": "_",
    "you score": "_",
    "paren": "(",
    "darren": ")",
    "round": "(",
    "invoke": "(",
    "sound": ")",
    "hound": ")",
    "squirrel": "{",
    "squirrely": "{",
    "girl": "}",
    "girly": "}",
    "slice": "[",
    "dice": "]",
    "rice": "]",
    "scope": "::",
    "period": ".",
    "dot": ".",
    "prick": ".",
    "punk": ".",
    "space": " ",
    "leader": " ",
    "assign": " = ",
    "follow": "->",
    "arrow": " -> ",
    "dub arrow": " => ",
    "left arrow": " <- ",
    "plus equal": " += ",
    "minus equal": " -= ",
    "remainder equal": " %= ",
    "percent equal": " %= ",
    "slash equal": " /= ",
    "star equal": " *= ",
    "is equal": " == ",
    "is less": " < ",
    "is lesseek": " <= ",
    "is greater": " > ",
    "is greatereek": " >= ",
    "plus": " + ",
    "minus": " - ",
    "slash": "/",
    "remainder": " % ",
    "percent": " % ",
    "scope": "::",
    "logic and": " && ",
    "logic or": " || ",
}

@mod.action_class
class Actions:
    def smart(text: str, init_formatter: str):
        current_formatter = init_formatter

